# Generated by Django 4.2 on 2023-04-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="tipo_telefone",
            field=models.CharField(
                choices=[("Tr", "Trabalho"), ("Ce", "Celular"), ("Ca", "Casa")],
                default="Tr",
                max_length=2,
            ),
        ),
    ]
