# Generated by Django 4.2 on 2023-04-25 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0002_contato_tipo_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="dt_atualizacao",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="contato",
            name="dt_criacao",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
