# Generated by Django 4.2 on 2023-04-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0003_contato_dt_atualizacao_contato_dt_criacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contato",
            name="tipo_telefone",
            field=models.CharField(
                choices=[("Trabalho", "Tr"), ("Celular", "Ce"), ("Casa", "Ca")],
                default="Tr",
                max_length=50,
            ),
        ),
    ]
