# Generated by Django 4.2 on 2023-04-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0004_alter_contato_tipo_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="foto_contato",
            field=models.ImageField(blank=True, upload_to="agenda/contatos/"),
        ),
        migrations.AlterField(
            model_name="contato",
            name="tipo_telefone",
            field=models.CharField(
                choices=[
                    ("Trabalho", "Trabalho"),
                    ("Celular", "Celular"),
                    ("Casa", "Casa"),
                ],
                default="Tr",
                max_length=50,
            ),
        ),
    ]
