# Generated by Django 4.2 on 2023-04-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0005_contato_foto_contato_alter_contato_tipo_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contato",
            name="tipo_telefone",
            field=models.CharField(
                choices=[
                    ("Trabalho", "Trabalho"),
                    ("Celular", "Celular"),
                    ("Casa", "Casa"),
                ],
                default="Trabalho",
                max_length=50,
            ),
        ),
    ]
